# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FalhaDePlantio
                                 A QGIS plugin
 --REMASTERIZADO --- Pluing utilizado para mapeamento de falha de plantio na cultura de cana de açúcar
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-25
        copyright            : (C) 2026 CainC0de
        email                : email
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'CainC0de'
__date__ = '2022-09-25'
__copyright__ = '(C) 2026 by CainC0de'


# noinspection PyPep8Naming
def classFactory(iface):  
    """Load FalhaDePlantio class from file FalhaDePlantio.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Falhadeplantio import FalhaDePlantioPlugin
    return FalhaDePlantioPlugin()
