# -*- coding: utf-8 -*-

"""
/***************************************************************************
 FalhaDePlantio
                                 A QGIS plugin
 Pluing utilizado para mapeamento de falha de plantio na cultura de cana de açúcar
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 
        copyright            : 
        email                : email
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Geo'
__date__ = '0'
__copyright__ = ""


___revision__ = '$Format:%H$'

import os
from qgis.core import QgsProcessingProvider
from qgis.PyQt.QtGui import QIcon

from .Falhadeplantio_algorithm import FalhaDePlantioAlgorithm
from .alg_extrair_linhas import ExtracaoLinhasAlgorithm

class FalhaDePlantioProvider(QgsProcessingProvider):

    def __init__(self):
        QgsProcessingProvider.__init__(self)

    def unload(self):
        pass

    def loadAlgorithms(self):
        """
        Registra os dois algoritmos separadamente na Caixa de Ferramentas.
        """
        self.addAlgorithm(ExtracaoLinhasAlgorithm()) # Ferramenta 1
        self.addAlgorithm(FalhaDePlantioAlgorithm())   # Ferramenta 2

    def id(self):
        return 'falha_plantio_cana'

    def name(self):
        return 'OpenGeoSource Team - Análise de Plantio'

    def icon(self):
        curr_dir = os.path.dirname(__file__)
        icon_path = os.path.join(curr_dir, 'canaicone.png')
        if os.path.exists(icon_path):
            return QIcon(icon_path)
        return QgsProcessingProvider.icon(self)

    def longName(self):
        return self.name()